### ISSUE TITLE
Wrong Redmine report for users without timezone preference

### ISSUE THREAD

**Issue by yelidrissi** [jigarius/toggl2redmine#29]
If you display a screen for a certain date, Francois Barbanson Aug.09 2018 for example. The items already in Redmine shown in the first box are for Aug.08 2018, not for Aug.09

**Comment by fbarbanson** [comment]
The fix is to add a documentation note telling users to set their Timezone in their Redmine profile.

**Comment by jigarius** [comment]
When you're focused on the date field, the tooltip asks you to update your timezone on Redmine and Toggl. There's one more place I can include it though. I'll do that asap.

**Comment by jigarius** [comment]
Now the plugin forces the user to configure a timezone if they don't have one configured. This should resolve the problem.

**Comment by jigarius** [comment]
Since all Redmine reports show incorrect data after setting a timezone preference in the user profile, I had to find a workaround for this problem. It turns out that one can send a complete ISO date time string in the format `2018-08-15T00:00:00Z` to make queries with UTC date and time. Having switched to this format, Redmine has given me correct data with and without setting a timezone preference in my account. This should solve the problem.
