### ISSUE TITLE
Imports marked as failed are actually imported into Redmine

### ISSUE THREAD

**Issue by mic79** [jigarius/toggl2redmine#32]
When importing a Toggl time entry into Redmine and the status "Failed" is given (e.g.: "Toggl ID has already been imported"), the (duplicate) time entry is being added to Redmine anyway (on Demo environment).

**Comment by jigarius** [comment]
Rails transactions do not behave like PHP + MySQL transactions. With that in mind, I rewrote the code such that:

* Before anything is saved to the database, a check is performed to see if any of the Toggl time entries already exists in the database. If yes, then the import fails without writing anything to the database.
* If none of the Toggl time entries are present in the database, entries are created and mapped.
* If anything goes wrong during the process, the Redmine time entry is deleted from the database and all the Toggl mappings are also deleted.

I tried reimporting time entries many times, but the plugin doesn't let me reimport them any more. Please let me know if you still face the problem.

**Comment by jigarius** [comment]
As I had suspected, the code was actually correct. However, our installation of Redmine didn't have support for database transactions. We need to switch from `MyISAM` to `InnoDB` to get transaction support.

Here are some changes which were addressed to solve this issue:
* Database transaction support requirements are now mentioned in the *Installation* section of the README.
* If transactions are not supported, an additional error message is shown to the user saying:
>Your database does not support transactions. Please ask your system administrator to refer to the README for "Toggle 2 Redmine".

This should take care of the problem for good. Rails doesn't provide any way of determining if the database supports transactions, otherwise, we could have shown a better error message. But having mentioned the issue in the README, the person installing the plugin should take care of this problem during installation.
