### ISSUE TITLE
Difference between Toggl and Redmine total time

### ISSUE THREAD

**Issue by kporras07** [jigarius/toggl2redmine#59]
**Bug summary**
When there are multiple entries in Toggl with some seconds here and there, the totals between Redmine and Toggl don't match because of seconds leftovers.

**To Reproduce**
1. Have several entries in Toggl with some seconds:
  - \# 1 Description 1:  0:01:36
  - \# 1 Description 2:  0:01:16
  - \# 1 Description 3:  0:02:26
  - \# 1 Description 4:  0:03:13
2. Import time into Redmine
3. Compare totals between Redmine and Toggl. If seconds differences are enough, you should have some minutes differences.
  - Toggl: 8.52 min (0.14h)
  - Redmine: 7 min (0.10h)

**Expected behavior**
Not sure.

**Additional context**
I was looking into the code to try to add rounding option for 1 minute, then I found that L1741 in assets/javascripts/t2r.js is using "imprecise" to remove leftovers seconds.

2 possible changes with this:
- Add option to round to 1 minute: the field could be changed to select to add the new option.
- Would you agree on changing that imprecise to false in case rounding is set to 1 minute?

Please let me know your thoughts on this. I would like to collaborate with a fix for this if that makes sense to you

**Comment by jigarius** [comment]
Thank you for reporting the issue. I'll take a look at it as soon as I have time.

**Comment by jigarius** [comment]
I think I should finally have some time to get this fixed. Here is some more info I could use:
- The issue description suggests *have several entries in Toggl with some seconds*. May I request you to give me a specific number? For example, Create 3 time entries on Toggl with durations 4s, 2s, and 5s.
- In a similar way, point number 3 could use some actual data (otherwise, I'll have to try to reproduce the bug by trial and error). For example, *the time on Toggl should be 11s, but the time on Redmine should be 1m*.

If I can have this info tomorrow, I'll try to work on it tomorrow night. Thanks 👍🏽

**Comment by kporras07** [comment]
@jigarius description updated with details. Thanks for looking into this

**Comment by jigarius** [comment]
## Findings

- I logged the exact time that you gave me and here's what I got:
  - 1m 36s is rounded to 1m in Redmine
  - 1m 16s is rounded to 1m in Redmine
  - 2m 26s is rounded to 2m in Redmine
  - 3m 13s is rounded to 3m in Redmine

## Constraints

- Toggl can keeps duration as seconds, while we have to round it to minutes because Redmine can only take hours and minutes.

## Proposed solution

### Update default rounding

The thing that can be fixed is the first entry, i.e. if a time entry on Toggl has more than 30s, T2R can round it up to the next minute. Example:
- 1m 15s -> 1m
- 1m 30s -> 2m
- 1m 35s -> 2m

I'll try to get this done as soon as possible.

### Use duration rounding

There is already an option to alter the rounding behavior, which I think might help you. In the *Advanced options* of Toggl 2 Redmine,
  - Try setting _Duartion rounding_ to _Round up_ (always go to the next minute) or _Round off_ (round to the next minute if 30s or more).
  - Set the rounding value to `1`, i.e. `1` minute.

**Comment by jigarius** [comment]
@kporras07 please try out the branch associated with https://github.com/jigarius/toggl2redmine/pull/69 and let me know if it works for you.

**Note to self:** Gotta redo the JS someday so that it can be tested. Or maybe create a plugin that doesn't rely on Toggl.

**Comment by kporras07** [comment]
It works as expected. Thanks :)

**Comment by jigarius** [comment]
@kporras07 inspired by this issue, I rewrote most of the JavaScript. The good news is that the duration rounding mechanism is now unit-tested. If you have time, please feel free to test ~Toggl 2 Redmine v5.0.0~ [Toggl 2 Redmine v4.4.0](https://github.com/jigarius/toggl2redmine/releases/tag/v4.4.0-beta.1).

**Comment by kporras07** [comment]
Hi @jigarius sure! Is it https://github.com/jigarius/toggl2redmine/releases/tag/v4.4.0-beta.1 the right tag? I can't find the one you linked

**Comment by jigarius** [comment]
Yes. That is the right tag. I had to remove the other one.

**Comment by jigarius** [comment]
Yes. That is the right tag. I had to remove the other one.

**Comment by kporras07** [comment]
I did some basic testing including rounding time entries and everything seems to be working. Do you want me to test something specific or is this enough?

As usual, thanks for all of the work in this great plugin!

**Comment by jigarius** [comment]
Nothing specific. If everything works normally as earlier, that should suffice. I basically moved things around and used Typescript to do the JavaScript stuff.
